name: Comunicador de la legion
on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Que villano envia el mensaje"
        required: true
        type: choice
        options:
          - lex luthor
          - magneto
          - joker
          - Mystique
          - Brainiac

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar el transmisor de la legion
        run: sudo apt-get install -y cosway
      - name: Imprimir inputs
        run: |
          echo "======================"
          echo " Transmision interceptada"
          echo "====================="
          echo "De: ${{inputs.villano}}"
          cowsay -f eyes "${{inputs.mensaje}}"
          echo ""
          echo "---- ${{inputs.villano}}"
